language: scala

os:
  - linux
jdk:
  - oraclejdk8
  - oraclejdk9

sudo: required
dist: trusty
group: edge

install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - mvn install -P travis -B -f driver/pom.xml -Dfailsafe.timeout=0
  - cd tests-scala ; sbt test
